### ISSUE TITLE
Метод pop обеспечивает базовую гарантию

### ISSUE THREAD

**Issue by simplydesigner** [TAHK6e3TOPMO3OB/STACK#6]
https://github.com/TAHK6e3TOPMO3OB/STACK/blob/29d07661bba2fb939fa9294dec27a3d89250980e/include/stack.cpp#L72

**Comment by TAHK6e3TOPMO3OB** [comment]
https://github.com/TAHK6e3TOPMO3OB/STACK/commit/60dbf039136dca8b1ac23548c73aa7bd55f25713
